"""extend users table with employee fields

Revision ID: 701db4e4bdba
Revises: f1f8d2e51d98
Create Date: 2026-07-14 14:48:42.132511
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701db4e4bdba'
down_revision: Union[str, None] = 'f1f8d2e51d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'

    with op.batch_alter_table('messages') as batch_op:
        batch_op.create_index(op.f('ix_messages_created_at'), ['created_at'], unique=False)
        if not is_sqlite:
            batch_op.drop_constraint(op.f('messages_applicant_id_fkey'), type_='foreignkey')
            batch_op.create_foreign_key('fk_messages_applicant_id', 'applicants', ['applicant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('progress_history') as batch_op:
        if not is_sqlite:
            batch_op.drop_constraint(op.f('fk_progress_history_applicant_id'), type_='foreignkey')
            batch_op.create_foreign_key('fk_progress_history_applicant_id', 'applicants', ['applicant_id'], ['id'])

    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('employee_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('designation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_logout', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_users_employee_code'), ['employee_code'], unique=True)
        batch_op.create_foreign_key('fk_users_created_by', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_employee_code'), table_name='users')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'last_logout')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'profile_photo')
    op.drop_column('users', 'department')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'employee_code')
    op.drop_constraint(None, 'progress_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_progress_history_applicant_id'), 'progress_history', 'applicants', ['applicant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_applicant_id_fkey'), 'messages', 'applicants', ['applicant_id'], ['id'])
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    # ### end Alembic commands ###
